on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    name: Go Tests
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.2'

      # Run unit tests
      - run: go test -v -coverprofile=profile.cov ./...

      # Coveralls
      - uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov
